import FWCore.ParameterSet.Config as cms

from Analysis.VLQAna.PickGenPart_cfi import *

massReco = cms.EDFilter("MassReco",
    met      = cms.InputTag("metFull", "metFullPt"),
    elPt     = cms.InputTag("electrons", "elPt"),
    elEta    = cms.InputTag("electrons", "elEta"),
    elPhi    = cms.InputTag("electrons", "elPhi"),
    elE      = cms.InputTag("electrons", "elE"),
    muPt     = cms.InputTag("muons", "muPt"),
    muEta    = cms.InputTag("muons", "muEta"),
    muPhi    = cms.InputTag("muons", "muPhi"),
    muE      = cms.InputTag("muons", "muE"),
		ak8jets  = cms.InputTag("ana", "ak8jets"),
    jets     = cms.InputTag("ana", "jets"),
    bjets    = cms.InputTag("ana", "bjets"),
    zjets    = cms.InputTag("ana", "wjets"),
    hjets    = cms.InputTag("ana", "hjets"),
    zllcands = cms.InputTag("ana", "zllcands"),
    evtwt    = cms.InputTag("ana", "finalWeight"),
    bcUp     = cms.InputTag("anabcUp", "finalWeight"),
    bcDown   = cms.InputTag("anabcDown", "finalWeight"),
    lUp      = cms.InputTag("analightUp", "finalWeight"),
    lDown    = cms.InputTag("analightDown", "finalWeight"),
    sbcUp    = cms.InputTag("anasbcUp", "finalWeight"),
    sbcDown  = cms.InputTag("anasbcDown", "finalWeight"),
    slUp     = cms.InputTag("anaslightUp", "finalWeight"),
    slDown   = cms.InputTag("anaslightDown", "finalWeight"),
    puUp     = cms.InputTag("anaPileupUp", "finalWeight"),
    puDown   = cms.InputTag("anaPileupDown", "finalWeight"),
    JECUp    = cms.InputTag("anaJecUp", "finalWeight"),
    JECDown  = cms.InputTag("anaJecDown", "finalWeight"),
    JERUp    = cms.InputTag("anaJerUp", "finalWeight"),
    JERDown  = cms.InputTag("anaJerDown", "finalWeight"),
    scaleUp  = cms.InputTag("anaScaleUp", "finalWeight"),
    scaleDown= cms.InputTag("anaScaleDown", "finalWeight"),
    DYdownLabel   = cms.InputTag("anaDYdown", "finalWeight"),
    tauUpLabel    = cms.InputTag("anatauUp", "finalWeight"),
    tauDownLabel  = cms.InputTag("anatauDown", "finalWeight"),
    st       = cms.InputTag("ana", "st"),
		STMin    = cms.double(1000.),
		STMaxControl = cms.double(1000.),
    ptMin    = cms.double(0.),
    zdecaymode = cms.string('zmumu'),
    signalType = cms.string(''),
		optimizeReco = cms.bool(False),
		controlReco = cms.bool(False),
    doSkim   = cms.bool(False),
    btagbcSFup = cms.bool(False),
    btagbcSFdown = cms.bool(False),
    btaglSFup = cms.bool(False),
    btaglSFdown = cms.bool(False),
    sbtagbcSFup = cms.bool(False),
    sbtagbcSFdown = cms.bool(False),
    sbtaglSFup = cms.bool(False),
    sbtaglSFdown = cms.bool(False),
    pileupUp = cms.bool(False),
    pileupDown = cms.bool(False),
    JECup = cms.bool(False),
    JECdown = cms.bool(False),
    JERup = cms.bool(False),
    JERdown = cms.bool(False),
    ScaleUp = cms.bool(False),
    ScaleDown = cms.bool(False),
    DYdown = cms.bool(False),
    tauUp     = cms.bool(False),
    tauDown   = cms.bool(False),


 		genParams = getSelectParams,	
 
   )
